"use server";

import { auth, signIn, signOut } from "@/auth";
import { AuthService } from "@/services/auth";
import { serverActionHandler } from "@/utils/serverAction";

/**
 * Authenticates the user via the NextAuth credentials provider and redirects
 * to the dashboard on success. Wrapped by {@link serverActionHandler} so the
 * return value is always a {@link ServerActionResult}.
 *
 * @param email    - The user's email address
 * @param password - The user's plain-text password
 * @returns A {@link ServerActionResult} with `success: true` on login or
 *          `success: false` with an error message on failure
 * @throws Only network-level errors re-thrown by {@link signIn}; application
 *         errors (bad credentials, missing user) are caught and returned as
 *         failure objects
 */
export const loginAction = serverActionHandler(async (email: string, password: string) => {
  await signIn("credentials", { email, password, redirectTo: "/dashboard" });
});

/**
 * Registers a new account, then immediately signs the user in and redirects
 * to the dashboard. The password is hashed server-side by
 * {@link AuthService.register}. Wrapped by {@link serverActionHandler}.
 *
 * @param data - Registration payload
 * @param data.email    - The new user's email address
 * @param data.password - The new user's plain-text password (min 8 characters)
 * @param data.username - Optional display name; a random hex string is
 *                        generated by {@link UserService.createUser} when omitted
 * @returns A {@link ServerActionResult} with `success: true` on completion or
 *          `success: false` with an error (e.g. "User is already registered")
 */
export const registerAction = serverActionHandler(
  async (data: { email: string; password: string; username?: string }) => {
    const authService = await AuthService.Instance(null);
    await authService.register(data);
    await signIn("credentials", {
      email: data.email,
      password: data.password,
      redirectTo: "/dashboard",
    });
  },
);

/**
 * Destroys the current session via NextAuth and redirects the user to the
 * login page. Wrapped by {@link serverActionHandler}.
 *
 * @returns A {@link ServerActionResult} with `success: true` on logout or
 *          `success: false` if the session could not be destroyed
 */
export const logoutAction = serverActionHandler(async () => {
  await signOut({ redirectTo: "/login" });
});

/**
 * Marks the currently authenticated user's account as verified. Reads the
 * user ID from the session, then delegates to
 * {@link AuthService.verifyAccount}. Wrapped by {@link serverActionHandler}.
 *
 * @returns A {@link ServerActionResult} with `success: true` once verified,
 *          or `success: false` if the user is already verified or the session
 *          is missing
 */
export const verifyAccountAction = serverActionHandler(async () => {
  const authService = await AuthService.Instance(null);
  await authService.verifyAccount((await auth().then((s) => s?.user?.id)) as string);
});
