"use server";

import { auth, signIn, signOut } from "@/auth";
import { AuthService } from "@/services/auth";
import { serverActionHandler } from "@/utils/serverAction";

/**
 * Authenticates the user via the NextAuth credentials provider and redirects
 * to the dashboard on success. Wrapped by {@link serverActionHandler} so the
 * return value is always a {@link ServerActionResult}.
 *
 * @param email    - The user's email address
 * @param password - The user's plain-text password
 * @returns A {@link ServerActionResult} with `success: true` on login or
 *          `success: false` with an error message on failure
 * @throws Only network-level errors re-thrown by {@link signIn}; application
 *         errors (bad credentials, missing user) are caught and returned as
 *         failure objects
 */
export const loginAction = serverActionHandler(async (email: string, password: string) => {
  await signIn("credentials", { email, password, redirectTo: "/dashboard" });
});

/**
 * Registers a new account via {@link AuthService.register}, then immediately
 * signs the user in with the credentials provider and redirects to the
 * dashboard. The password is hashed server-side; the caller receives a
 * plain-text password that never hits the database.
 *
 * Wrapped by {@link serverActionHandler} so every outcome is a
 * {@link ServerActionResult}.
 *
 * @param data          - Registration payload
 * @param data.email    - The new user's email address
 * @param data.password - Plain-text password (must be at least 8 characters;
 *                        the caller does its own client-side check as well)
 * @param data.username - Optional display name. When omitted a random hex
 *                        string is generated by the user service.
 * @returns A {@link ServerActionResult} with `success: true` once the user is
 *          registered and signed in, or `success: false` with an error message
 *          such as "User is already registered".
 * @throws Network-level errors re-thrown by {@link signIn}; application errors
 *         (duplicate email, weak password) are caught and returned as failure
 *         objects.
 */
export const registerAction = serverActionHandler(
  async (data: { email: string; password: string; username?: string }) => {
    const authService = await AuthService.Instance(null);
    await authService.register(data);
    await signIn("credentials", {
      email: data.email,
      password: data.password,
      redirectTo: "/dashboard",
    });
  },
);

/**
 * Destroys the current session via NextAuth and redirects the user to the
 * login page. Wrapped by {@link serverActionHandler}.
 *
 * @returns A {@link ServerActionResult} with `success: true` on logout or
 *          `success: false` if the session could not be destroyed
 */
export const logoutAction = serverActionHandler(async () => {
  await signOut({ redirectTo: "/login" });
});

/**
 * Marks the currently authenticated user's account as verified. Extracts the
 * user ID from the session and delegates to
 * {@link AuthService.verifyAccount}. Wrapped by {@link serverActionHandler}.
 *
 * @param token - The verification token extracted from the URL path. Must
 *                match the token stored when the account was created.
 * @returns A {@link ServerActionResult} with `success: true` once the account
 *          is marked verified, or `success: false` if the user is already
 *          verified, the session is missing, or the token is invalid.
 */
export const verifyAccountAction = serverActionHandler(async (token: string) => {
  const authService = await AuthService.Instance(null);
  await authService.verifyAccount((await auth().then((s) => s?.user?.id)) as string, token);
});

/**
 * Sends a new verification email to the currently authenticated user. Reads
 * the user's email from the session and delegates to
 * {@link AuthService.sendVerificationEmail}. Wrapped by
 * {@link serverActionHandler}.
 *
 * @returns A {@link ServerActionResult} with `success: true` when the email is
 *          dispatched, or `success: false` if the session is missing or the
 *          email service is unavailable.
 */
export const resendVerificationEmailAction = serverActionHandler(async () => {
  const authService = await AuthService.Instance(null);
  await authService.sendVerificationEmail((await auth().then((s) => s?.user?.email)) as string);
});
